/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noyou (https://sketchfab.com/zsm123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ancient-chinese-courtyard-park-55d8371278844dbbbe43e1f867b5fcde
Title: Ancient Chinese courtyard Park
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FF01_zhuan04jpg_0: THREE.Mesh
    FF02_KHFC_07jpg_0: THREE.Mesh
    FF03_tingzhiyuan_09jpg_0: THREE.Mesh
    FF04_dingzhiyi3jpg_0: THREE.Mesh
    FF05_loupng_0: THREE.Mesh
    FF06_tingzhiyuan_02jpg_0: THREE.Mesh
    FF07_KHFC_09jpg_0: THREE.Mesh
    FF08_tingzhiyuan_01jpg_0: THREE.Mesh
    FF09_KHFC_06png_0: THREE.Mesh
    ['FF10_YZY-09_0']: THREE.Mesh
    FF11_cezhiyijpg_0: THREE.Mesh
    FF12_KHFC_01jpg_0: THREE.Mesh
    FF13_wall04jpg_0: THREE.Mesh
    FF14_huzhongqiaojpg_0: THREE.Mesh
    FF15_fangcong_tingzipng_0: THREE.Mesh
    FF16_fangcong_fangzi02jpg_0: THREE.Mesh
    FF16_fangcong_fangzi02jpg_0_1: THREE.Mesh
    FF16_fangcong_fangzi02jpg_0_2: THREE.Mesh
    FF17_fangcong_fangzijpg_0: THREE.Mesh
    FF17_fangcong_fangzijpg_0_1: THREE.Mesh
    FF18_jiashan02jpg_0: THREE.Mesh
    FF19_zawu01png_0: THREE.Mesh
    FF20_zhuan05jpg_0: THREE.Mesh
    FF21_zhuan03jpg_0: THREE.Mesh
    FF23_Yazhiyuan06jpg_0: THREE.Mesh
    FF24_zhuan01jpg_0: THREE.Mesh
    FF22_zhuan02jpg_0: THREE.Mesh
  }
  materials: {
    ['zhuan04.jpg']: THREE.MeshStandardMaterial
    ['KHFC_07.jpg']: THREE.MeshStandardMaterial
    ['tingzhiyuan_09.jpg']: THREE.MeshStandardMaterial
    ['dingzhiyi3.jpg']: THREE.MeshStandardMaterial
    ['lou.png']: THREE.MeshStandardMaterial
    ['tingzhiyuan_02.jpg']: THREE.MeshStandardMaterial
    ['KHFC_09.jpg']: THREE.MeshStandardMaterial
    ['tingzhiyuan_01.jpg']: THREE.MeshStandardMaterial
    ['KHFC_06.png']: THREE.MeshStandardMaterial
    ['YZY-09']: THREE.MeshStandardMaterial
    ['cezhiyi.jpg']: THREE.MeshStandardMaterial
    ['KHFC_01.jpg']: THREE.MeshStandardMaterial
    ['wall04.jpg']: THREE.MeshStandardMaterial
    ['huzhongqiao.jpg']: THREE.MeshStandardMaterial
    ['fangcong_tingzi.png']: THREE.MeshStandardMaterial
    ['fangcong_fangzi02.jpg']: THREE.MeshStandardMaterial
    ['fangcong_fangzi.jpg']: THREE.MeshStandardMaterial
    ['jiashan02.jpg']: THREE.MeshStandardMaterial
    ['zawu01.png']: THREE.MeshStandardMaterial
    ['zhuan05.jpg']: THREE.MeshStandardMaterial
    ['zhuan03.jpg']: THREE.MeshStandardMaterial
    ['Yazhiyuan06.jpg']: THREE.MeshStandardMaterial
    ['zhuan01.jpg']: THREE.MeshStandardMaterial
    ['zhuan02.jpg']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'public/ancient_chinese_courtyard_park/sceneDraco.gltf'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF01_zhuan04jpg_0.geometry}
          material={materials['zhuan04.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF02_KHFC_07jpg_0.geometry}
          material={materials['KHFC_07.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF03_tingzhiyuan_09jpg_0.geometry}
          material={materials['tingzhiyuan_09.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF04_dingzhiyi3jpg_0.geometry}
          material={materials['dingzhiyi3.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF05_loupng_0.geometry}
          material={materials['lou.png']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF06_tingzhiyuan_02jpg_0.geometry}
          material={materials['tingzhiyuan_02.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF07_KHFC_09jpg_0.geometry}
          material={materials['KHFC_09.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF08_tingzhiyuan_01jpg_0.geometry}
          material={materials['tingzhiyuan_01.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF09_KHFC_06png_0.geometry}
          material={materials['KHFC_06.png']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FF10_YZY-09_0'].geometry}
          material={materials['YZY-09']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF11_cezhiyijpg_0.geometry}
          material={materials['cezhiyi.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF12_KHFC_01jpg_0.geometry}
          material={materials['KHFC_01.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF13_wall04jpg_0.geometry}
          material={materials['wall04.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF14_huzhongqiaojpg_0.geometry}
          material={materials['huzhongqiao.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF15_fangcong_tingzipng_0.geometry}
          material={materials['fangcong_tingzi.png']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <group position={[1736.315, -945.103, -41.102]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FF16_fangcong_fangzi02jpg_0.geometry}
            material={materials['fangcong_fangzi02.jpg']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FF16_fangcong_fangzi02jpg_0_1.geometry}
            material={materials['fangcong_fangzi02.jpg']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FF16_fangcong_fangzi02jpg_0_2.geometry}
            material={materials['fangcong_fangzi02.jpg']}
          />
        </group>
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <group position={[1736.315, -945.103, -41.102]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FF17_fangcong_fangzijpg_0.geometry}
            material={materials['fangcong_fangzi.jpg']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FF17_fangcong_fangzijpg_0_1.geometry}
            material={materials['fangcong_fangzi.jpg']}
          />
        </group>
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF18_jiashan02jpg_0.geometry}
          material={materials['jiashan02.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF19_zawu01png_0.geometry}
          material={materials['zawu01.png']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF20_zhuan05jpg_0.geometry}
          material={materials['zhuan05.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF21_zhuan03jpg_0.geometry}
          material={materials['zhuan03.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF23_Yazhiyuan06jpg_0.geometry}
          material={materials['Yazhiyuan06.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF24_zhuan01jpg_0.geometry}
          material={materials['zhuan01.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
      <group
        position={[9.104, 3.684, 14.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FF22_zhuan02jpg_0.geometry}
          material={materials['zhuan02.jpg']}
          position={[1736.315, -945.103, -41.102]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('public/ancient_chinese_courtyard_park/sceneDraco.gltf')
