/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-hallwyl-museum-1st-floor-combined-f74eefe9f1cd4a2795a689451e723ee9
Title: The Hallwyl Museum 1st Floor Combined
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Great_Drawing_Room_0: THREE.Mesh
    Great_Drawing_Room_0_1: THREE.Mesh
    Armoury_0: THREE.Mesh
    Dining_Room_0: THREE.Mesh
    Morning_Room_0: THREE.Mesh
    Upper_Vestibule_0: THREE.Mesh
    Smoking_Room_0: THREE.Mesh
    Small_Drawing_Room_0: THREE.Mesh
    Billiard_Room_0: THREE.Mesh
    Porcelain_Room_0: THREE.Mesh
    Porcelain_Room_0_1: THREE.Mesh
    Serving_Room_0: THREE.Mesh
    Floor_Plan_0: THREE.Mesh
    ['Small_Drawing_Room_-_Mirror_0']: THREE.Mesh
  }
  materials: {
    Great_Drawing_Room: THREE.MeshBasicMaterial
    Armoury: THREE.MeshBasicMaterial
    Dining_Room: THREE.MeshBasicMaterial
    Morning_Room: THREE.MeshBasicMaterial
    Upper_Vestibule: THREE.MeshBasicMaterial
    Smoking_Room: THREE.MeshBasicMaterial
    Small_Drawing_Room: THREE.MeshBasicMaterial
    Billiard_Room: THREE.MeshBasicMaterial
    Porcelain_Room: THREE.MeshBasicMaterial
    Serving_Room: THREE.MeshBasicMaterial
    Floor_Plan: THREE.MeshBasicMaterial
    Mirror: THREE.MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/modelDraco.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
        <group
          position={[0.553, -9.413, 3.573]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.239}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Great_Drawing_Room_0.geometry}
            material={materials.Great_Drawing_Room}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Great_Drawing_Room_0_1.geometry}
            material={materials.Great_Drawing_Room}
          />
        </group>
        <group
          position={[5.07, 2.039, 3.198]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.127}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Porcelain_Room_0.geometry}
            material={materials.Porcelain_Room}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Porcelain_Room_0_1.geometry}
            material={materials.Porcelain_Room}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Armoury_0.geometry}
          material={materials.Armoury}
          position={[4.289, -5.871, 3.193]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.131}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dining_Room_0.geometry}
          material={materials.Dining_Room}
          position={[-4.197, -1.024, 3.514]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.206}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Morning_Room_0.geometry}
          material={materials.Morning_Room}
          position={[0.579, -5.796, 3.34]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Upper_Vestibule_0.geometry}
          material={materials.Upper_Vestibule}
          position={[-3.27, -5.771, 2.379]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.169}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Smoking_Room_0.geometry}
          material={materials.Smoking_Room}
          position={[5.224, -9.662, 3.543]}
          rotation={[Math.PI / 2, 1.568, 0]}
          scale={0.148}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Small_Drawing_Room_0.geometry}
          material={materials.Small_Drawing_Room}
          position={[-4.28, -9.589, 3.416]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.142, 0.145, 0.145]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Billiard_Room_0.geometry}
          material={materials.Billiard_Room}
          position={[5.144, -1.387, 3.382]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.202}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Serving_Room_0.geometry}
          material={materials.Serving_Room}
          position={[-4.06, 2.611, 2.945]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.1, 0.105, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Plan_0.geometry}
          material={materials.Floor_Plan}
          position={[-0.052, -0.117, -2.14]}
          rotation={[0, 0, Math.PI / 2]}
          scale={14.314}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Small_Drawing_Room_-_Mirror_0'].geometry}
          material={materials.Mirror}
          position={[-4.321, -8.135, 3.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.015}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/modelDraco.gltf')
